### ISSUE TITLE
Metamodel of Ecore is not supported 

### ISSUE THREAD

**Issue by vnikitch** [ferdjoukh/grimm#1]
Using the uploaded file as a metamodel (extension changed from .ecore to txt because of github limitations) I want to generate different metamodels
[Ecore.txt](https://github.com/ferdjoukh/grimm/files/2526505/Ecore.txt)

But generator gives me an error: 
CSP Solver is running... Not OK :(
	CSP instance is unsatisfiable :(

![error](https://user-images.githubusercontent.com/16878274/47671303-e0187f00-dbb7-11e8-8d05-f2a1c45c1961.png)

Here is my params file:
![params](https://user-images.githubusercontent.com/16878274/47671467-3980ae00-dbb8-11e8-8177-eeb356ee11c3.png)

#
Does your generator support generation of instances of ecore metamodel (Ecore.ecore) ?
If yes, could you provide some configuration examples for this case ?

**Comment by ferdjoukh** [comment]
Hello,

It is an interesting issue. First I give you one configuration file I built and that is SAT.

[ecoreparams.txt](https://github.com/ferdjoukh/grimm/files/2563500/ecoreparams.txt)

The problem with this file is during Model Building and It is related to changeable references in the meta-model. I will change that tomorrow and build a new release.

**Comment by ferdjoukh** [comment]
Grimm [v3.0](https://github.com/ferdjoukh/grimm/releases/tag/v3.0-d9112018) solves somme of these problems.

But there is a remaining issue with containment relations. Indeed, currently it is not possible to have containment between classes (except from rootClass). So the issue is still open.

But now you can generate small ecore Models.

Lower bound is preferably 1. it seems that there is a bug with 0.

**Comment by vnikitch** [comment]
Hello,

Ok, I wait for a final working release

I have a question about a number of elements in generated model. I expect to generate model containing up to 200 000 elements. Does your tool support the generating of such large models ?

**Comment by ferdjoukh** [comment]
Hello,

The problems you encountered are now solved by the last version of grimm [4.0](https://github.com/ferdjoukh/grimm/releases/tag/v4.0-d15112018).

For the size of generated ecore, I think that it is possible but may be long. Btw, You should use [configuration file](https://github.com/ferdjoukh/grimm/blob/master/README.md#configuration-file) instead of quick parameter mode. This way you have more control on the models you want to generate.

Please tell me if this is convenient for you. Thank you very much for your useful feedback.
